/* This file is generated by Ziggy. */
declare module 'ziggy-js' {
  interface RouteList {
    "filament.exports.download": [
        {
            "name": "export",
            "required": true,
            "binding": "id"
        }
    ],
    "filament.imports.failed-rows.download": [
        {
            "name": "import",
            "required": true,
            "binding": "id"
        }
    ],
    "filament.auth\/admin.auth.login": [],
    "filament.auth\/admin.auth.logout": [],
    "filament.auth\/admin.pages.dashboard": [],
    "filament.auth\/admin.resources.billboards.index": [],
    "filament.auth\/admin.resources.billboards.create": [],
    "filament.auth\/admin.resources.billboards.edit": [
        {
            "name": "record",
            "required": true
        }
    ],
    "livewire.update": [],
    "livewire.upload-file": [],
    "livewire.preview-file": [
        {
            "name": "filename",
            "required": true
        }
    ],
    "home": [],
    "billboards.index": [],
    "billboards.show": [
        {
            "name": "billboard",
            "required": true,
            "binding": "id"
        }
    ],
    "about": [],
    "contact.index": [],
    "contact.submit": [],
    "newsletter.subscribe": [],
    "newsletter.unsubscribe": [
        {
            "name": "token",
            "required": true
        }
    ],
    "storage.local": [
        {
            "name": "path",
            "required": true
        }
    ]
}
}
export {};
